### ISSUE TITLE
大佬想问一下这个safefolder没有删除功能对吧

### ISSUE THREAD

**Issue by yuhaolin-10** [Magi2B0y/NewNotes#2]
<img width="620" alt="屏幕截图 2024-05-10 153703" src="https://github.com/Magi2B0y/NewNotes/assets/139048798/bca4ba89-226d-4268-98e1-ba4722234c92">

<img width="234" alt="屏幕截图 2024-05-10 153749" src="https://github.com/Magi2B0y/NewNotes/assets/139048798/69ac3337-b3fe-43b2-b3d8-c5548432faa3">

**Comment by Magi2B0y** [comment]
代码细节我也记不太清了，safefolder应该是有一个独立于原项目的数据库的文件，safefolder数据变化操作应该都在那个文件里里写着，如果没有delete那可能就是没写



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Magi2B0y/NewNotes] 大佬想问一下这个safefolder没有删除功能对吧 (Issue #2)




 2024-05-10.153703.png (view on web) 2024-05-10.153749.png (view on web)

**Comment by yuhaolin-10** [comment]
safefoldeactivity文件里好像确实是没有delete这个操作，感谢
